version: 2

updates:
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps
    assignees:
      - lukasgro63

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: deps
    assignees:
      - lukasgro63
    ignore:
      - dependency-name: next
        update-types:
          - version-update:semver-major
      - dependency-name: react
        update-types:
          - version-update:semver-major
      - dependency-name: react-dom
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: deps
    assignees:
      - lukasgro63

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps
    assignees:
      - lukasgro63

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps
    assignees:
      - lukasgro63
