stages:
    - build
    - test
    - deploy

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""



build-to-deploy:
    image: docker/compose:1.29.2
    services:
        - docker:dind
    tags:
        - prod
    stage: build

    before_script:
        - chmod +x set_environment.sh
        - source set_environment.sh
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker-compose -f $DOCKER_COMPOSE_FILE build
        - docker-compose -f $DOCKER_COMPOSE_FILE push
    only:
        - main


#deploy-to-prod:
#    stage: deploy
#    tags:
#        - prod_runner
#    script:
#        - ssh $SERVER_USERNAME@$SERVER_IP "mkdir -p $APP_PATH"
#        - scp $DOCKER_COMPOSE_FILE $SERVER_USERNAME@$SERVER_IP:$APP_PATH/docker-compose.yml
#        - scp docker-compose.prod.yml $SERVER_USERNAME@$SERVER_IP:$APP_PATH/docker-compose.prod.yml
#        - ssh $SERVER_USERNAME@$SERVER_IP "cd $APP_PATH && docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
#    only:
#        - main





#build:
#    stage: build
#    image: docker/compose:1.29.2
#    services:
#        - docker:dind
#    before_script:
#        - echo "DOCKER_COMPOSE_FILE is set to:" $DOCKER_COMPOSE_FILE
#        - echo "Building Docker images using the following compose files:" $DOCKER_COMPOSE_FILE
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    script:
#       - docker-compose -f $DOCKER_COMPOSE_FILE build
#       - docker-compose -f $DOCKER_COMPOSE_FILE push
#   only:
#       - main
#       - test



#backend-test:
#    stage: test
#    image: docker/compose:1.29.2
#    services:
#        - docker:dind
#    before_script:
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    script:
#        
#        - docker pull $CI_REGISTRY_BACKEND_IMAGE:latest
#        - docker run $CI_REGISTRY_BACKEND_IMAGE:latest python test_backend.py
#    only:
#        - main
#        - test
