version: '3'
services:
  backend:
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DEV_ENVIRONMENT=true
  frontend:
    ports:
      - "4200:4200"
    environment:
      - DEBUG=1

      
