version: '3'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: $CI_REGISTRY_BACKEND_IMAGE:latest
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: $CI_REGISTRY_FRONTEND_IMAGE:latest
